(map (lambda (x) (hash-ref x 'name)) 
     (hash-ref (response-json (get "https://api.kinopio.club/space/TBn3RkhMIs7ksoX64sYWu"))
	       'cards))

Kinopio space needs authorization, or, needs to be shared

Kinopio API https://help.kinopio.club/api/

model code for simple access: https://github.com/bentsai/kinopio-to-markdown

```
> res
'#hasheq((background . "")
         (backgroundTint . "")
         (boxes . ())
         (cards
          .
          (#hasheq((backgroundColor . null)
                   (createdAt . "2023-05-07T13:07:20.305Z")
                   (frameId . 0)
                   (id . "0Oqc7lt0Wz7PaHYejSVD2")
                   (isComment . #f)
                   (isCreatedThroughPublicApi . #f)
                   (isLocked . #f)
                   (isRemoved . #f)
                   (linkToSpaceId . null)
                   (name . "command2")
                   (nameUpdatedAt . "2023-05-07T13:07:24.244Z")
                   (nameUpdatedByUserId . "5My83_-9fXJKx6a3cuq8s")
                   (resizeWidth . null)
                   (shouldHideUrlPreviewImage . #f)
                   (shouldHideUrlPreviewInfo . #f)
                   (shouldUpdateUrlPreview . #f)
                   (spaceId . "TBn3RkhMIs7ksoX64sYWu")
                   (updatedAt . "2023-05-07T13:07:24.244Z")
                   (urlPreviewDescription . null)
                   (urlPreviewErrorUrl . null)
                   (urlPreviewFavicon . null)
                   (urlPreviewImage . null)
                   (urlPreviewIsVisible . #t)
                   (urlPreviewTitle . null)
                   (urlPreviewUrl . null)
                   (userId . "5My83_-9fXJKx6a3cuq8s")
                   (x . 318)
                   (y . 180)
                   (z . 4))
           #hasheq((backgroundColor . null)
                   (createdAt . "2023-05-07T13:07:10.324Z")
                   (frameId . 0)
                   (id . "m_HP763y9wwm4vpdXjB0s")
                   (isComment . #f)
                   (isCreatedThroughPublicApi . #f)
                   (isLocked . #f)
                   (isRemoved . #f)
                   (linkToSpaceId . null)
                   (name . "command1")
                   (nameUpdatedAt . "2023-05-07T13:07:17.338Z")
                   (nameUpdatedByUserId . "5My83_-9fXJKx6a3cuq8s")
                   (resizeWidth . null)
                   (shouldHideUrlPreviewImage . #f)
                   (shouldHideUrlPreviewInfo . #f)
                   (shouldUpdateUrlPreview . #f)
                   (spaceId . "TBn3RkhMIs7ksoX64sYWu")
                   (updatedAt . "2023-05-07T13:07:17.339Z")
                   (urlPreviewDescription . null)
                   (urlPreviewErrorUrl . null)
                   (urlPreviewFavicon . null)
                   (urlPreviewImage . null)
                   (urlPreviewIsVisible . #t)
                   (urlPreviewTitle . null)
                   (urlPreviewUrl . null)
                   (userId . "5My83_-9fXJKx6a3cuq8s")
                   (x . 123)
                   (y . 157)
                   (z . 3))
           #hasheq((backgroundColor . null)
                   (createdAt . "2023-05-07T09:21:05.153Z")
                   (frameId . 0)
                   (id . "nYOXovJc-64TQdOS4quig")
                   (isComment . #f)
                   (isCreatedThroughPublicApi . #f)
                   (isLocked . #f)
                   (isRemoved . #f)
                   (linkToSpaceId . null)
                   (name . "card A - content")
                   (nameUpdatedAt . "2023-05-07T12:17:59.328Z")
                   (nameUpdatedByUserId . "5My83_-9fXJKx6a3cuq8s")
                   (resizeWidth . null)
                   (shouldHideUrlPreviewImage . #f)
                   (shouldHideUrlPreviewInfo . #f)
                   (shouldUpdateUrlPreview . #f)
                   (spaceId . "TBn3RkhMIs7ksoX64sYWu")
                   (updatedAt . "2023-05-07T12:17:59.329Z")
                   (urlPreviewDescription . null)
                   (urlPreviewErrorUrl . null)
                   (urlPreviewFavicon . null)
                   (urlPreviewImage . null)
                   (urlPreviewIsVisible . #t)
                   (urlPreviewTitle . null)
                   (urlPreviewUrl . null)
                   (userId . "5My83_-9fXJKx6a3cuq8s")
                   (x . 205)
                   (y . 83)
                   (z . 2))))
         (collaborators . ())
         (connectionTypes
          .
          (#hasheq((color . "rgb(249, 161, 129)")
                   (createdAt . "2023-05-07T12:17:46.129Z")
                   (id . "PBgZ7dhV83SlL-E52UDTa")
                   (name . "Across")
                   (spaceId . "TBn3RkhMIs7ksoX64sYWu")
                   (updatedAt . "2023-05-07T13:17:48.284Z"))))
         (connections
          .
          (#hasheq((connectionTypeId . "PBgZ7dhV83SlL-E52UDTa")
                   (controlPoint . "q00,00")
                   (createdAt . "2023-05-07T13:07:27.729Z")
                   (directionIsVisible . #t)
                   (endCardId . "0Oqc7lt0Wz7PaHYejSVD2")
                   (id . "BZYk4rVTROYRoAL7qRBrI")
                   (labelIsVisible . #f)
                   (path . "m222,173 q00,00 195,23")
                   (spaceId . "TBn3RkhMIs7ksoX64sYWu")
                   (startCardId . "m_HP763y9wwm4vpdXjB0s")
                   (updatedAt . "2023-05-07T13:15:34.714Z")
                   (userId . "5My83_-9fXJKx6a3cuq8s"))))
         (createdAt . "2023-05-07T09:20:48.898Z")
         (editedAt . "2023-05-07T13:07:24.244Z")
         (editedByUserId . "5My83_-9fXJKx6a3cuq8s")
         (id . "TBn3RkhMIs7ksoX64sYWu")
         (isFromTweet . #f)
         (isHidden . #f)
         (isRemoved . #f)
         (isTemplate . #f)
         (moonPhase . "")
         (name . "pttest")
         (originSpaceId . "")
         (privacy . "closed")
         (proposedShowInExplore . #f)
         (removedByUserId . null)
         (showInExplore . #f)
         (showInExploreUpdatedAt . "2023-05-01T07:50:47.866Z")
         (tags . ())
         (updateHash . "b1cED6ZuVmhj17STedDS-")
         (updatedAt . "2023-05-07T13:07:27.729Z")
         (url . "pttest-TBn3RkhMIs7ksoX64sYWu")
         (userId . "5My83_-9fXJKx6a3cuq8s")
         (users
          .
          (#hasheq((color . "#ffc1f3")
                   (description . null)
                   (id . "5My83_-9fXJKx6a3cuq8s")
                   (isDonor . null)
                   (isGuideMaker . #f)
                   (isModerator . #f)
                   (isUpgraded . #t)
                   (name . "Paul")
                   (website . null))))
         (visits . 11))
>
```
